version: '3'

services:
  postgres:
    image: 'postgres:14.8'
    container_name: postgres
    hostname: postgres
    restart: always
    privileged: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1qazXSW@
      - POSTGRES_DB=postgres
    volumes:
      - ./volumes/data:/var/lib/postgresql/data:rw
    networks:
      - postgres-network
networks: 
  postgres-network:
    driver: bridge