version: '3'

services:
  postgres:
    image: 'postgres:14.8'
    container_name: postgres
    hostname: postgres
    restart: always
    privileged: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1qazXSW@
    volumes:
      - ./volumes/data:/var/lib/postgresql/data:rw