services:
  oracle23:
    # https://container-registry.oracle.com/
    image: container-registry.oracle.com/database/free:23.9.0.0-lite-arm64
    container_name: oracle23
    hostname: oracle23
    # network_mode: host # 设置网络模式为主机模式(端口映射无效)
    restart: no # always | no | on-failure
    privileged: false
    ports:
      - 15210:1521
    environment:
      # 密码规范：8个字符，至少包含1个大写字母、1个小写字母和1个数字[0-9]
      ORACLE_PWD: Oracle123
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ../../my-docker-volumes/oracle23/data:/opt/oracle/oradata
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      default: 
        aliases:
          - oracle23_net
networks:
  default:
    name: docker_default_net
    external: true