services:
  postgres17:
    image: postgres:17.5-alpine3.22 # https://github.com/docker-library/docs/blob/master/postgres/README.md
    container_name: postgres17
    hostname: postgres17
    # network_mode: host # 设置网络模式为主机模式(端口映射无效)
    restart: no # always | no | on-failure
    privileged: false
    ports:
      - 54320:5432
    shm_size: 128mb
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1qaz<LP_
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "5"