version: '3'

services:
  odoo18:
    image: odoo:18
    platform: linux/amd64 # 如果是 Apple Silicon 需要指定该配置
    container_name: odoo18
    hostname: odoo18
    restart: no # always | no | on-failure
    privileged: false
    ports:
      - 8069:8069
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf:/etc/odoo
      - ../../my-docker-volumes/odoo18/data:/var/lib/odoo
      - ../../my-docker-volumes/odoo18/addons:/mnt/extra-addons
    networks:
      default: 
        aliases:
          - odoo18_net
networks:
  default:
    name: mynet_default
    external: true