version: '3'

services:
  odoo:
    image: odoo:17
    platform: linux/amd64 # 如果是 Apple Silicon 需要指定该配置
    container_name: odoo17
    hostname: odoo17
    restart: no # always | no | on-failure
    privileged: false
    ports:
      - 8069:8069
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf:/etc/odoo
      - ./volumes/data:/var/lib/odoo
      - ./volumes/addons:/mnt/extra-addons
    networks:
      default: 
        aliases:
          - odoo17_net
networks:
  default:
    name: mynet_default
    external: true