version: '3'

services:
  postgres15:
    image: 'postgres:15.5'
    container_name: postgres15
    hostname: postgres15
    restart: no # always | no | on-failure
    privileged: false
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1qazXSW@
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    networks:
      default: 
        aliases:
          - postgres15_net
networks:
  default:
    name: mynet_default
    external: true