# https://hub.docker.com/_/redis?tab=tags
version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/data:/var/lib/grafana:rw
      - ./volumes/plugins:/var/lib/grafana/plugins:rw
    networks:
      - net_db
networks:
  net_db:
    driver: bridge