version: '2'

services:
  oceanbase:
    #platform: linux/amd64 # 如果是 Apple Silicon 需要指定该配置
    image: oceanbase/oceanbase-ce:latest # 使用OceanBase社区版的最新镜像，请根据实际情况替换版本号
    container_name: oceanbase
    user: root  # 使用root用户
    mem_limit: 7000M
    mem_reservation: 6500M
    ports:
      - "2881:2881" # OBServer RPC端口
      - "2882:2882" # SQL客户端访问端口
      - "2883:5000" # OBProxy端口，如果需要的话
    command: ["mkdir -p /root/ob && chmod 777 /root/ob"]
    environment:
      - MINI_MODE=1 # 容器规格 0-最大规格实例, 1-部署 mini 的独立实例
      - ROOT_PASSWORD=root # 设置root用户的密码
      - TZ=Asia/Shanghai # 设置时区，可根据需要调整
    volumes:
      - ./volumes/data:/root/ob  # 挂载数据卷，用于持久化数据
      - ./nproc.conf:/etc/security/limits.d/nproc.conf