services:
  mysql8:
    image: mysql:8.4.6 # https://github.com/docker-library/docs/blob/master/mysql/README.md
    container_name: mysql8
    hostname: mysql8
    # network_mode: host # 设置网络模式为主机模式(端口映射无效)
    restart: always # 容器是否自动重启, always | no | on-failure
    privileged: false
    command: 
      --mysql_native_password=on
      --character_set_server=utf8mb4
      --collation_server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --transaction_isolation=Read-Committed
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      --max_connections=100
      --wait_timeout=28800
      --interactive_timeout=28800
      --max_allowed_packet=128M
      --innodb_buffer_pool_size=256M
      --innodb_redo_log_capacity=256M
      --innodb_flush_method=O_DIRECT
      --innodb_flush_log_at_trx_commit=2
      --skip_log_bin
      --default_time_zone='+8:00'
      --open_files_limit=1000
      --table_open_cache=400
      --tmp_table_size=64M
      --max_heap_table_size=64M
      --skip_name_resolve
      --performance_schema=ON
    volumes:
      - ../../my-docker-volumes/mysql8/data:/var/lib/mysql # 数据
      - ../../my-docker-volumes/mysql8/conf/:/etc/mysql/conf.d # 配置
      - ../../my-docker-volumes/mysql8/mysql-files:/var/lib/mysql-files
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1qaz<LP_
    ports:
      - 33060:3306
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    networks:
      default: 
        aliases:
          - mysql8_net
networks:
  default:
    name: docker_default_net
    external: true