# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  ########################## 服务器 ###########################
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.250:9100', '192.168.1.251:9100', '192.168.1.252:9100', '192.168.1.253:9100', '192.168.1.254:9100']

  ######################## MySQL #############################
  - job_name: 'mysqld_exporter'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets: ['192.168.1.250:9104', '192.168.1.251:9104']

  ######################## Docker #############################
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.253:9080']
    metrics_path: '/metrics'

  ######################## Spring Boot App #############################
  - job_name: 'wms-app'
    static_configs:
      - targets: ['192.168.1.253:8086']
    metrics_path: '/wms/actuator/prometheus'
  
  - job_name: 'wms-ga-app'
    static_configs:
      - targets: ['192.168.1.253:8085']
    metrics_path: '/wmsga/actuator/prometheus'

  - job_name: 'wms-med-app'
    static_configs:
      - targets: ['192.168.1.253:8088']
    metrics_path: '/wmsmed/actuator/prometheus'

  - job_name: 'wes-app'
    static_configs:
      - targets: ['192.168.1.253:8010']
    metrics_path: '/wes/actuator/prometheus'

  - job_name: 'wcs-app'
    static_configs:
      - targets: ['192.168.1.253:8089']
    metrics_path: '/wcs/actuator/prometheus'

  - job_name: 'les-app'
    static_configs:
      - targets: ['192.168.1.253:8087']
    metrics_path: '/les/actuator/prometheus'

  - job_name: 'pfep-app'
    static_configs:
      - targets: ['192.168.1.253:8084']
    metrics_path: '/pfep/actuator/prometheus'