# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  ########################## 服务器 ###########################
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.250:9100', '192.168.1.251:9100']

  ######################## MySQL #############################
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['192.168.1.250:9104', '192.168.1.251:9104']