# https://hub.docker.com/_/redis?tab=tags
version: '3'

services:
  redis:
    image: redis:7.4.5
    container_name: redis7
    hostname: redis7
    restart: always # always | no | on-failure
    privileged: false
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/redis.conf:/usr/local/redis/redis.conf
      - ./volumes/data:/data
    command:
      redis-server /usr/local/redis/redis.conf
    networks:
      default: 
        aliases:
          - redis7_net
networks:
  default:
    name: mynet_default
    external: true