# https://hub.docker.com/_/redis?tab=tags
version: '3'

services:
  redis:
    image: redis:6.0.6
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - net_db
    volumes:
      - ./volumes/conf/redis.conf:/etc/redis/redis.conf:rw
      - ./volumes/data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes # --requirepass redis 
networks:
  net_db:
    driver: bridge