# https://hub.docker.com/_/redis?tab=tags
version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    privileged: true
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/conf/redis.conf:/usr/local/redis/redis.conf:rw
      - ./volumes/data:/data:rw
    command:
      redis-server /usr/local/redis/redis.conf